batch_size: 16
caid_path: dataset/
categories:
- non-binding
- binding
data_path: dataset/
dataset: binding
datasets_to_test:
- dev
- caid3/binding
- caid3/binding_idr
debug: false
disprot_version: 25-12
dropout_rate: 0.1
emb_size: 352
energy_emb_path: /home/sduarte/embeddings/binding/energy/
filters: 150
kernel_size: 7
lr: 3.0e-05
n_resnet: 1
nepoch: 500
patience: 10
plm: esm2_6m
plm_emb_path: /home/sduarte/embeddings/binding/esm2_6m/
reduce_method: weighted-scaled
soft_max: true
subset: cv10_nr_seed42_wo-test/fold_8
win_len: 34
id: trial24_filt150_ker7_resnet1_win34_lr3e-05_drop0.10_28-06-2026_01-16-52